### ISSUE TITLE
Some misunderstandings about adjacent sibling combinator (+) as alternative way of using :not() pseudo-class

### ISSUE THREAD

**Issue by RinatValiullov** [AllThingsSmitty/css-protips#105]
There is some alternative approach In the section about `:not()` CSS pseudo-class :
[Use :not() to Apply/Unapply Borders on Navigation](https://github.com/AllThingsSmitty/css-protips#use-not-to-applyunapply-borders-on-navigation)

> Sure, you can use `.nav li + li`, but with `:not()` the intent is very clear and the CSS selector defines the border the way a human would describe it.

I think this _adjacent sibling combinator_ has a different meaning(inner logic) rather than `:not()` CSS pseudo-class. Of course in the context of the **Borders on Navigation**.
What I mean? 

If we apply _adjacent sibling combinator_:
```js
.nav li + li {
  border-right: 1px solid #666;
}
```
We will have border-right on the `li` elements except the first one. [example pen](https://codepen.io/4rontender/pen/LqwdyN)

But with `:not()` pseudo-class we will have right behaviour:
```js
.nav li:not(:last-child) {
  border-right: 1px solid #666;
}
```

Question: Can we replace _pseudo-class_ with _adjacent sibling combinator_? Or there's some error here? Or I didn't catch intent of this CSS tip?

**Comment by AllThingsSmitty** [comment]
@RinatValiullov I do see where the confusion lies, because if I said `li:not(:first-child)`, it'd make more sense. I'll have look it over and maybe remove that blurb to avoid confusion.

**Comment by RinatValiullov** [comment]
Ok :thumbsup:
@AllThingsSmitty 
But I thought that you meant similar behaviour of `+` combinator and `:not()`, isn't it? 
`border-right` prop is associated with the extreme right element (`:last-child`), not `first-child`
There's still some misunderstanding for me.

**Comment by AllThingsSmitty** [comment]
@RinatValiullov `:not()` isn't the same as the adjacent sibling selector. `:not()` is a pseudo-class, and represents elements that don't match a list of selectors.

**Comment by RinatValiullov** [comment]
I know that it's not the same. That's why I  made this issue-question.

But I want to understand what did you mean when wrote this:

> Sure, you can use `.nav li + li`,..

alongside this tip?

Maybe you can clear this approach for others, who didn't understand your intention and think that these constructions are the same (of course it's not)?
