### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by manolasn** [AllThingsSmitty/css-protips#118]
Hello I've started translating in Greek it will take me until tomorrow to have it ready should i wait and make a PR as soon as  the whole translation is ready or should I make I PR as i progress (sorry for asking such a question,beginner with github here :D)

**Comment by AllThingsSmitty** [comment]
You can always pulled the latest master and start again. Be sure to follow the steps in the [Contributing](https://github.com/AllThingsSmitty/css-protips/blob/master/CONTRIBUTING.md#language-translations) section for language translations (create a new directory under Translations following the same pattern as the others for that language).
