### ISSUE TITLE
Alternative to "Use :not() to Apply/Unapply Borders on Navigation"

### ISSUE THREAD

**Issue by Frinsh** [AllThingsSmitty/css-protips#12]
Same outcome for all of these solutions but less code and better browser support (IE7+ instead of IE9+)

```
.nav li + li {
  border-left: 1px solid #666;
}
```

**Comment by AllThingsSmitty** [comment]
@Frinsh correct, but the intent of that tip was mainly to showcase the use of `:not()`.

**Comment by Frinsh** [comment]
@AllThingsSmitty but the adjacent sibling selector solution does not use this.
