### ISSUE TITLE
Edge now supports "all" keyword

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [AllThingsSmitty/css-protips#132]
At https://github.com/AllThingsSmitty/css-protips#use-unset-instead-of-resetting-all-properties, it says "the `all` shorthand isn't supported in IE11 and is currently under consideration for support in Edge"

It looks like Edge now supports the `all` keyword, probably because it's now based on Chromium 🙂

Source: https://caniuse.com/css-all

**Comment by AllThingsSmitty** [comment]
Thanks!
