### ISSUE TITLE
Add tip: Using Aspect Ratio instead of usual Margin and Padding

### ISSUE THREAD

**Issue by farheen21** [AllThingsSmitty/css-protips#141]
I think this repo must contain the aspect ratio hack...It can be use widely in hero section , responsive styling and grid based content....
Here is more info about the [aspect ratio hack](https://css-tricks.com/almanac/properties/a/aspect-ratio/)
please do let me know if its best fit for the repo and if yes I would like to send a PR for this

**Comment by AllThingsSmitty** [comment]
@farheen21 thanks for the suggestion. I hadn't consider `aspect-ratio`, but feel free to submit a PR and I'll review it.

**Comment by vinaybharadwaj007** [comment]
Pr

**Comment by robsonsobral** [comment]
`aspect-ratio` isn't a hack, but a standard CSS property. I can't see a reason for consider it a tip.

**Comment by tusharrajpoot** [comment]
@AllThingsSmitty can you assign it to me?

**Comment by mansi142003** [comment]
can you assign to me?

**Comment by princesingh04** [comment]
can you assign this to me
