### ISSUE TITLE
Suggesting another use of :not()

### ISSUE THREAD

**Issue by ed1nh0** [AllThingsSmitty/css-protips#16]
Not an issue, just a suggestion.
Since you're already using `:not()` on two of those pro tips, I'd suggest to use it on another one:

The **Select Items Using Negative nth-child**:

    li {
        display: none;
    }

    /* select items 1 through 3 and display them */
    li:nth-child(-n+3) {
        display: block;
    }

Could be *just*:

    /* select items 1 through 3 and display them */
    li:not(:nth-child(-n+3)) {
        display: none;
    }

Thanks for sharing those!

**Comment by AllThingsSmitty** [comment]
@ed1nh0 I like that. It has a consistent feeling throughout the tip suggestions. 👍🏼

**Comment by AllThingsSmitty** [comment]
Added in https://github.com/AllThingsSmitty/css-protips/commit/8c21696e2da7789e35c58fab038a0e3668803a9a.
