### ISSUE TITLE
Good practices about :root

### ISSUE THREAD

**Issue by brunowego** [AllThingsSmitty/css-protips#17]
I see some projects using `:root` but I not have any idea about good practices about it. Have any tip for us?

**Comment by AllThingsSmitty** [comment]
@brunowego I'll look into that.

**Comment by brunowego** [comment]
Thanks @AllThingsSmitty :+1:

**Comment by AllThingsSmitty** [comment]
@brunowego I haven't found anything specific on this to-date, but I'll keep looking.

**Comment by AllThingsSmitty** [comment]
Added tip: b7e0bd5fac11879bc4e0bc75ee27086bfbac8b7e

**Comment by brunowego** [comment]
👍
