### ISSUE TITLE
Demos FTW!

### ISSUE THREAD

**Issue by plainspace** [AllThingsSmitty/css-protips#18]

**Comment by Frozenfire92** [comment]
+1, I couldn't figure out the pure css slider

**Comment by manumorante** [comment]
:+1:

**Comment by NipSauce** [comment]
Yes please!

**Comment by vikrantnegi** [comment]
Indeed great suggestion.

**Comment by AllThingsSmitty** [comment]
Working on it. :+1:

**Comment by AllThingsSmitty** [comment]
I've demos for about half the tips. Some I may not do if they are self-explanatory enough, or if they have links to articles where demos already exist.

Thanks for the suggestion. I should've done this sooner. 🍾 🎉 💃🏻
