### ISSUE TITLE
List of links, can't add style with CSS

### ISSUE THREAD

**Issue by DevBeginner1** [AllThingsSmitty/css-protips#181]
Hi.
I am new with web development.
I try to make a list of links, which consists to put all links on the top of a page, on one line, to have something like this.

![links](https://github.com/AllThingsSmitty/css-protips/assets/111196043/c5aff881-6a40-424f-a20a-ac67daefdf18)

Here is the HTML code :
`
<html>
    <head>
        <meta lang="en">
        <meta charset="utf-8">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        {% block head %}

        {% endblock %}
    </head>
    <body>
        <ul id="list1">
            <li><a href="{{url_for('home_page')}}">Home</a></li>
            <li><a href="{{url_for('current_projects')}}">Current projects</a></li>
            <li><a href="{{url_for('about')}}">About us</a></li>
            <li><a href="{{url_for('contacts')}}">Contacts</a></li>
            <li><a href="{{url_for('help')}}">Help</a></li>
        </ul>

        {% block body %}

        {% endblock %}
    </body>
</html>
`

But when I try to add styles to list elements ith css, nothing happens.

Thanks for your help.

**Comment by AllThingsSmitty** [comment]
Hi, your question isn't specific to the content in this repo. You will have a better chance of finding an answer if you post your question on Stackoverflow.
