### ISSUE TITLE
Consider adding lobotomized owl (* + *) margin style

### ISSUE THREAD

**Issue by mrwweb** [AllThingsSmitty/css-protips#19]
http://alistapart.com/article/axiomatic-css-and-lobotomized-owls

> we adopt the aforementioned universal selector, creating our owl face. The axiom is as follows: “All elements in the flow of the document that proceed other elements must receive a top margin of one line."

```css
* + * {
	margin-top: 1.5em;
}
```

**Comment by albertorestifo** [comment]
:+1:

**Comment by AllThingsSmitty** [comment]
@mrwweb I like the idea. Let me see how to best work it in. Thanks.

**Comment by AllThingsSmitty** [comment]
Added with commit https://github.com/AllThingsSmitty/css-protips/commit/9544b8d46a2585b31e2338e9dc604ce559f144cf.

**Comment by fabsn182** [comment]
How is this a pro tip? Floating- and inline-elements get the margin-top too, so you'll have to overwrite an expensive rule everytime you don't need it. Imho that's bad practise.

**Comment by sentience** [comment]
@fabsn182: inline elements ignore top and bottom margins applied to them.

As for floated elements, if you’re using floats for layouts then that standard margin applied to floated elements will often be desirable. Certainly, many devs find having that inter-block margin be the default that you can remove when needed is actually a sensible baseline to adopt. See http://vimeo.com/101718785 for a talk that features this technique prominently.

**Comment by fabsn182** [comment]
@sentience Two floating elements with 50% percent width each and the second one needs `margin-top:0`. So I am overwriting something that doesn't need to be in the CSSOM in the first place and you say that is desirable?
