### ISSUE TITLE
Readme upgrade

### ISSUE THREAD

**Issue by Yuheshpandian** [AllThingsSmitty/css-protips#190]
Hi @AllThingsSmitty just saw your project/Repository. I just want to inform that instead of creating a note section in README.md like this :

⚠️ Note:
••••

Like this you could try using this

```md
> [!Note]
> content•••••
```

The output would look like this:

> [!Note]
> Content•••

This would actually improve uniformity and look more appealing.

This is just a little suggestion.

Thank you

**Comment by AllThingsSmitty** [comment]
Interesting, I'll take a look at it.

**Comment by Yuheshpandian** [comment]
I saw the README upgrade it was 🔥.
Thank you for taking my suggestions into acount.

**Comment by investoricky** [comment]
Thanks I really appreciate
