### ISSUE TITLE
Consistent vertical rhythm within elements

### ISSUE THREAD

**Issue by alexcarpenter** [AllThingsSmitty/css-protips#20]
Use a global selector within an element to create a consistent vertical rhythm.
```
article > * {
  margin-bottom: 1.25rem;
}
```

**Comment by martinpesout** [comment]
I'm also using similar CSS definition. But I think that `article` selector is really general. I'm rather using more specific one. Something like this:

```
.typo >  * {
  margin-bottom: 1.25rem;
}
```

**Comment by alexcarpenter** [comment]
Yeah, I would typically use `.entry > *` since this would target *all* elements including figure, images, videos etc. not just typographic elements.

**Comment by AllThingsSmitty** [comment]
Commit https://github.com/AllThingsSmitty/css-protips/commit/bd16f8d122d060b479993a8d1af813bb01d92eb0. 👍🏼
