### ISSUE TITLE
Not a fan of the first :not tip

### ISSUE THREAD

**Issue by danielgamble** [AllThingsSmitty/css-protips#21]
I don't think the `:not` tip should be advised. You're adding 1 more level specificity to all of nav items except the last one as opposed to that 1 level to just the last one. Makes it a bit more annoying to overwrite when it comes to it.

**Comment by AllThingsSmitty** [comment]
@DanGamble89 I appreciate the feedback but I have to disagree. The additional specificity is negligible and one of the reasons I'm advising it is that the use of `:not(:last-child)` is very clear with the CSS selector defining the border the way a human would describe it.

**Comment by DanGamble89** [comment]
I wouldn't say it's negligible. Once you start having to style dropdowns on the same nav or style it different on mobile where there are no borders then you will hit conflicts. I use to be an advocate of this method but once you start implementing these things it just causes headaches.

If you have to style the asset responsively i'd go for child specific pseudo's as opposed to hitting all of them with a `:not`

**Comment by katgironpe** [comment]
I think if you're supporting IE9, stick to using classes and learn more than CSS. Not a good "PRO" tip.

**Comment by robsonsobral** [comment]
> I think if you're supporting IE, stick to using classes and learn more than CSS. Not a good "PRO" tip.

+1

**Comment by johnmcdowall** [comment]
I think if you're supporting IE, you should know that IE has supported :not since IE9. 

http://caniuse.com/#feat=css-sel3

**Comment by katgironpe** [comment]
I'm very much aware of that, thank you. I don't see the point of this PRO tips, honestly. I feel like avoiding selectors may even be a better practice.

**Comment by DanGamble89** [comment]
I'd say using selectors is bad practice too, stick to classes 100% unless you can't

**Comment by vwochnik** [comment]
> I'd say using selectors is bad practice too, stick to classes 100% unless you can't

Not sure if srs. The new CSS3 selectors are there so we can strip the HTML markup of unnecessary classes to make it cleaner and to further separate content from style. I have to say I like both the nav and inline list `:not()`  tip. I wasn't aware of the `:not()` selector before.

**Comment by kohenkatz** [comment]
> I'd say using selectors is bad practice too, stick to classes 100% unless you can't

@DanGamble89 What about if I want to style the first and/or last elements of a list differently? Should I add `first` and `last` classes instead of using selectors, because it "can" be done that way?

**Comment by DanGamble89** [comment]
Using pseudo selectors is fine, using HTML selectors i.e, div, span, h1 is bad practice.

`:first-child`, `:last-child` are totally fine. `:not()` can be okay as well. But in instances like this it's bad as it adds an extra level of specificity for little to no gain. It will cause you problems when you want to style dropdowns in the navigation or make the navigation responsive

**Comment by vwochnik** [comment]
@DanGamble89 then just don't use them for dropdowns!

Styling `div`s may not be advisable since a `div` is fairly generic but styling `h1` is just fine!

**Comment by AllThingsSmitty** [comment]
> It will cause you problems when you want to style dropdowns in the navigation or make the navigation responsive.

@DanGamble89 how so? Do you have an example of that so we can see if `:not()` is really the problem?

**Comment by AllThingsSmitty** [comment]
> styling h1 is just fine!

@vwochnik agreed, especially when you have to consider accessibility.
