### ISSUE TITLE
Please don't recommend disabling subpixel anti-aliasing everywhere

### ISSUE THREAD

**Issue by pornel** [AllThingsSmitty/css-protips#22]
```css
html {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
```

OS X has an option to disable "LCD font smoothing" in System Preferences, so those who don't like it can do so. But it doesn't have an option to force sharp text rendering on pages that chose to make it blurry.

Please don't recommend setting these properties on `html`. They do help to make icon fonts less wonky and for some fonts rendered in white-on-black, but in disabling it everywhere for everyone is IMHO too drastic.

**Comment by AllThingsSmitty** [comment]
@pornel thanks, I'll look into that further.

**Comment by AllThingsSmitty** [comment]
@pornel you're right, it's too risky now. I pulled it with commit https://github.com/AllThingsSmitty/css-protips/commit/9544b8d46a2585b31e2338e9dc604ce559f144cf. Thanks for bringing this up.
