### ISSUE TITLE
box-sizing inheritance questions

### ISSUE THREAD

**Issue by sweeperq** [AllThingsSmitty/css-protips#24]
Is there a reason the **html** rule comes before the **\*, \*:before, \*:after** rule instead of after it?

Also, I thought that it was considered bad practice to use the universal selector?

**Comment by AllThingsSmitty** [comment]
@sweeperq good question. I don't think it's not bad practice to use the universal selector, it's just one of those things devs need to be aware of how powerful it is.

In this example, using the universal selector with pseudo-elements improves the normalizing effect of `border-box`. But the universal selector makes it difficult to use the `content-box` and `padding-box` values of `box-sizing` elsewhere in your CSS.

However, by allowing `box-sizing` to be inherited from the `html` selector resolves this issue without worrying about a universal selector overriding your CSS.
