### ISSUE TITLE
Mention browser bugs with flexbox

### ISSUE THREAD

**Issue by wmertens** [AllThingsSmitty/css-protips#3]
Nice list!

With some tweaks all these tips work also with IE10, which still has large enough market share to care.

However, with IE10 flexbox centering fails when using min-height instead of height, see https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items

**Comment by AllThingsSmitty** [comment]
Good suggestion. Let me do a little testing with IE10 and I might add a link to that bug reference.

**Comment by AllThingsSmitty** [comment]
Added an IE11 flexbox bug note with 9119ef260e25d7f9eeec21c2625c8879b6f7f63b
