### ISSUE TITLE
Make a note that comma separated lists are not exactly semantically correct

### ISSUE THREAD

**Issue by iKlsR** [AllThingsSmitty/css-protips#32]
https://github.com/AllThingsSmitty/css-protips#comma-separated-lists

> Make list items look like a real, comma-separated list:

Looks fine for viewing but if the page is scraped or being looked at by a screen reader these will be missed.

**Comment by AllThingsSmitty** [comment]
Good point, thanks for the suggestion.

**Comment by AllThingsSmitty** [comment]
Commit https://github.com/AllThingsSmitty/css-protips/commit/6dc6252b937fcc689191174446d3d51f1cf569af.
