### ISSUE TITLE
* + * Incorrect verb: Precede.

### ISSUE THREAD

**Issue by rjksn** [AllThingsSmitty/css-protips#33]
Wouldn't this mean that "anything" that's after *anything* gets a margin on top? The opposite of precede — original reference document uses "proceed."

Suggested edit.
> In this example, all elements in the flow of the document that follow other elements will receive `margin-top: 1.5em`.

**Comment by AllThingsSmitty** [comment]
It's a valid point. Thanks. 👍🏼

**Comment by rjksn** [comment]
No worries, good list! :)

**Comment by AllThingsSmitty** [comment]
Commit https://github.com/AllThingsSmitty/css-protips/commit/a75231b8612bd41f5248d5ba850a0edd4b21b4fc.
