### ISSUE TITLE
Added tip: CSS Counters

### ISSUE THREAD

**Issue by Knogobert** [AllThingsSmitty/css-protips#34]
You should add a tip on little known (or remembered) CSS Counters i believe.

It is supported on all major platforms, [http://caniuse.com/#feat=css-counters](http://caniuse.com/#feat=css-counters)

Here is an example: [http://codepen.io/Monochrome/pen/bEMbdr](http://codepen.io/Monochrome/pen/bEMbdr)

**Comment by vikrantnegi** [comment]
Great suggestion of adding counters and nice pen on codepen. 
They can be used for other purposes as well.
Here is an example of counters being used to [progress tracker navigation](http://codepen.io/vikrantnegi007/pen/RWyZZQ). 
Link: http://codepen.io/vikrantnegi007/pen/RWyZZQ
