### ISSUE TITLE
Submit to awesome list?

### ISSUE THREAD

**Issue by sindresorhus** [AllThingsSmitty/css-protips#36]
This looks like a good addition for https://github.com/sindresorhus/awesome.

Would you be interested in submitting it there? See: https://github.com/sindresorhus/awesome/blob/master/create-list.md

**Comment by AllThingsSmitty** [comment]
@sindresorhus thanks, that's a great suggestion. Let me get the repo Awesome-ized and I'll submit a PR.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/commit/1223624e0f90572a176d2ee47b55a2f957672026
