### ISSUE TITLE
CSS-generated content can't be copied

### ISSUE THREAD

**Issue by edouard-lopez** [AllThingsSmitty/css-protips#37]
Related to #32, CSS-generated content isn't part of the selection. So when copy/pasting result might differ from what is displayed on the page.

Example: http://codepen.io/edouard-lopez/pen/VeoRre

**Comment by AllThingsSmitty** [comment]
@edouard-lopez thanks for your feedback. I agree it's worth noting the copy/paste doesn't work on CSS-generated content.

**Comment by AllThingsSmitty** [comment]
Commit https://github.com/AllThingsSmitty/css-protips/commit/9541b11f86e8b3756f73acada3e9aececd4c6589.
