### ISSUE TITLE
Please don't suggest to use px values for font-size

### ISSUE THREAD

**Issue by nhoizey** [AllThingsSmitty/css-protips#46]
[Use `rem` for Global Sizing; Use `em` for Local Sizing](https://github.com/AllThingsSmitty/css-protips#use-rem-for-global-sizing-use-em-for-local-sizing) -> YES!

But… `html { font-size: 16px; }` -> pleaaaase noooo! :-/

https://nicolas-hoizey.com/2016/03/people-don-t-change-the-default-16px-font-size-in-their-browser.html

**Comment by AllThingsSmitty** [comment]
@nhoizey thanks for the feedback. Your post is interesting. Are you advocating more for just `html { font-size: 1em; }` to let the default value be interited per browser?

**Comment by nhoizey** [comment]
@AllThingsSmitty thanks for reading it! ;-)

`html { font-size: 1em; }` is useless, as it is the default value. So I would advocate for nothing at all.

To be honest, I now use something [a little more complex](https://github.com/nhoizey/nicolas-hoizey.com/blob/master/_assets/stylesheets/critical.scss#L24) on the `body` to add some fluid responsiveness to my `font-size`, but I don't touch the `html` `font-size` at all and the value on `body` is meant to be equal to `1em` or more, depending on viewport sizes.
