### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by AllThingsSmitty** [AllThingsSmitty/css-protips#50]
I'm setting up this card as a way to track PR's for language translations. If you're translating this repo please add a comment indicating which language so we're not duplicating work. 😎

Your PR should include the following:
1. Add a language/country code folder to the `translations` folder, e.g., `translations/fr-FR`
2. Add a `README.md` file with the translation to the language/country code folder, e.g., `.../fr-FR/README.md`

You can find more information about contributing under the [Language Translations](https://github.com/AllThingsSmitty/jquery-tips-everyone-should-know/blob/master/CONTRIBUTING.md#language-translations) section of the Contribution Guidelines.

I'm not looking for pasting into Google Translate; I can do that myself and it's not accurate. 💁🏼 I appreciate your help with this. 👍🏼

---

Translations (and any others that may not be on this list):
- [x] Chinese - simplified (zh-CN)
- [x] Chinese - traditional (zh-TW)
- [x] French (fr-FR)
- [x] German (de-DE)
- [x] Greek (gr-GR)
- [x] Gujarati (gu-GU)
- [x] Italian (it-IT)
- [x] Japanese (ja-JP)
- [x] Korean (ko-KR)
- [x] Polish (pl-PL)
- [x] Portuguese - Brazilian  (pt-BR)
- [x] Portuguese - European (pt-PT)
- [x] Russian (ru-RU)
- [x] Spanish (es-ES)
- [x] Vietnamese (vn-VN)

**Comment by tomlutzenberger** [comment]
If I find time to do it, I could translate to German.

Just one question: What are the exact benefits of those translations? I mean... most programmers are able to read/speak english.

**Comment by AllThingsSmitty** [comment]
@tomlutzenberger most? Are you sure? If that's true then there's no benefit in doing the translations. Otherwise the benefit is reaching more devs.

**Comment by tomlutzenberger** [comment]
This was just an assumption. But I agree with your point on reaching more devs.
Alright, as soon as I find some time, I'll do this.

**Comment by anisa07** [comment]
Hello, 
I can translate to Russian :) if interestng

**Comment by AllThingsSmitty** [comment]
@anisa07 thank you so much, Anisa. I did a terrible job with the Russian translation, so you can overwrite what's in the `ru-RU` folder. I appreciated your help.

**Comment by anisa07** [comment]
Actually everything is fine! You are doing great job! Thanks! I will use it in my next projects:)

**Comment by AllThingsSmitty** [comment]
@anisa07 awesome! 👍🏼

**Comment by sotayamashita** [comment]
@AllThingsSmitty Japanese it not good. If there are no people who help this, I think it should not be here.

**Comment by AllThingsSmitty** [comment]
@sotoyamashita the translation isn't good? Hopefully people will help with it then.

**Comment by huzeyfeborazan** [comment]
I would like to help with Turkish translations

**Comment by SFromentarius** [comment]
Hi! 
I've read the French translation and I believe there are some mistakes in the translation (I'm a french native speaker). If I understood well how GitHub works, could I create a branch to make better the French translation? 
thanks

**Comment by AllThingsSmitty** [comment]
Yes, you can create a branch, make your changes, and then submit a pull request. Please review GutHub’s [documentation](https://help.github.com/articles/creating-a-pull-request/) to become more familiar with the process.

**Comment by Doctor-L** [comment]
I can take a look into Portuguese - (Pt-Br), and help with Spanish if needed

**Comment by AllThingsSmitty** [comment]
@TKO-berg sure, that would be great!

**Comment by Basheer88** [comment]
I can translate it to Arabic Language if you accept it.

**Comment by AllThingsSmitty** [comment]
@Basheer88 yes, that would be awesome, thanks!

**Comment by estellerostan** [comment]
Hello @AllThingsSmitty, 
I'm going to work on the french translation as it still need some improvements.
Keep up the good work! :+1:

**Comment by AllThingsSmitty** [comment]
@estellerostan terrific, thanks!

**Comment by estellerostan** [comment]
Thanks for the merge! :sparkles: :confetti_ball:

**Comment by AllThingsSmitty** [comment]
@paulina-grunwald thank you! Feel free to submit a PR with the corrections.

**Comment by paulina-grunwald** [comment]
I am on it. Will be done in max. 2 days.

**Comment by floppylab** [comment]
Hi there!
I would like to work on the Hungarian version! :)

**Comment by leonorader** [comment]
Hi there!
I would like to work on the Hungarian version! :)

**Comment by ashleymavericks** [comment]
It seems I can help in adding the Hindi Language! if it really helps.

**Comment by ConiWright** [comment]
I could do Hebrew if needed :)

**Comment by anishansari** [comment]
I could do Nepali if needed. let me know 
Thanks :)

**Comment by monzter50** [comment]
I could do Spanish if needed. let me know!

**Comment by AllThingsSmitty** [comment]
@monzter50 there's a Spanish folder (es-ES) but feel free to review and make corrections. Can't remember if someone did it or if I put it into Google Translate and effed it up.

**Comment by monzter50** [comment]
Jajaja lol, then he checked folder :)
Thank you.

**Comment by manolasn** [comment]
Hello I've started translating in Greek it will take me until tomorrow to have it ready should i wait and make a PR as soon as the whole translation is ready or should I make I PR as i progress (sorry for asking such a question,beginner with github here :D)

**Comment by KapilBansal320** [comment]
I can translate to Hindi. Let me knew if it works

**Comment by ve00ryca** [comment]
Hi there! :) I'd like to contribute for translations in Bulgarian (if interested).

**Comment by Vanshikaa00** [comment]
Hello !! I would like to translate in hindi

**Comment by rajamanojkumar** [comment]
Hello there, I would like to translate to Telugu. Let me know if i can start my work.

**Comment by AllThingsSmitty** [comment]
@rajamanojkumar yes, that would be great.

**Comment by gaweki** [comment]
i would like help translation into indonesian language. please let me know for work on it :)

**Comment by gaweki** [comment]
hey @AllThingsSmitty would you add indonesian language, if i translate it?

**Comment by RanimAmor** [comment]
Hello, @AllThingsSmitty i can translate in arabic language if you want.

**Comment by AllThingsSmitty** [comment]
@RanimAmor thanks for offering. I'm actually thinking about closing out this Issue and leaving the translations as they are. The difficulty is each time I update the main README I have to work at getting all the translations updated too. I think we have enough translations now to be beneficial.

**Comment by AllThingsSmitty** [comment]
Closing call for translations
