### ISSUE TITLE
Undefined measure unit in line-height section

### ISSUE THREAD

**Issue by superlativo77** [AllThingsSmitty/css-protips#58]
line-height: 1.5;

**Comment by AllThingsSmitty** [comment]
`line-height` shouldn't have a unit of measurement. Was it something else you were reporting?

**Comment by albertorestifo** [comment]
You can learn more on how `line-height` works and why it's highly recommended to keep it unitless here:

https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#Prefer_unitless_numbers_for_line-height_values
