### ISSUE TITLE
Add global font size

### ISSUE THREAD

**Issue by superlativo77** [AllThingsSmitty/css-protips#59]
html {
    font-size: 14px;
}
p {
    font-size: 1rem;
}

**Comment by AllThingsSmitty** [comment]
What is the issue you're reporting?

**Comment by albertorestifo** [comment]
Defining a font in pixel is bad practice. Users can define a different default font size in the browser, this will result in that setting not being respected.

**Comment by superlativo77** [comment]
@albertorestifo you are right but my proposal was based on this: https://css-tricks.com/rems-ems

**Comment by albertorestifo** [comment]
A better solution is to define the HTML font to be 100%, so we still leave the user in control:

```css
html {
  font-size: 100%;
}

p {
  font-size: 1rem;
}
```

**Comment by superlativo77** [comment]
It is true. Now I found your solution here:
https://www.sitepoint.com/understanding-and-using-rem-units-in-css

Thanks

**Comment by AllThingsSmitty** [comment]
I'll look into this further. Thanks.

**Comment by AllThingsSmitty** [comment]
Commit f333da1d285fa66a30ee79183ccd5463e81e7b99
