### ISSUE TITLE
about flex layout

### ISSUE THREAD

**Issue by flyinglove** [AllThingsSmitty/css-protips#63]
Using flex to do layout is pretty cool, but as the content goes more, there may be something wrong, for example, if I paste the h1  tag in your demo for 10 times, the document will only show it 9 times though there is a scroll bar, and if i decrease the browser's height, there will be more to lose, how could i solve this problem gracefully?

**Comment by AllThingsSmitty** [comment]
Is that a bug? You may want to check out @philipwalton's [flexbugs] repo. It covers a bunch of weird flexbox issues.
