### ISSUE TITLE
使用 “形似猫头鹰” 的选择器这个模块demo链接出错

### ISSUE THREAD

**Issue by byronlun** [AllThingsSmitty/css-protips#65]
使用 “形似猫头鹰” 的选择器这个模块demo链接出错了，翻译的时候搞错了吧，原文是正确的，原文demo链接是[这个](http://codepen.io/AllThingsSmitty/pen/grRvWq)，翻译的链接是[这个](http://codepen.io/AllThingsSmitty/pen/XKgOkR)

**Comment by AllThingsSmitty** [comment]
@shfshanyue, since you helped with the translation can you take a look at this issue? Thanks.

**Comment by byronlun** [comment]
@AllThingsSmitty , It means that the chinese translation in [this module](https://github.com/AllThingsSmitty/css-protips/tree/master/translations/zh-CN#use-the-lobotomized-owl-selector) have a error that the url of demo make a mistake.

**Comment by byronlun** [comment]
@AllThingsSmitty , there is a mistake in the chinses translation of [this module](https://github.com/AllThingsSmitty/css-protips/tree/master/translations/zh-CN#use-the-lobotomized-owl-selector) where the url of the demo is wrong.

**Comment by AllThingsSmitty** [comment]
@byronlun okay, I can take of that. Thanks for pointing it out. @shfshanue, I'll take care of this. Thanks!

**Comment by shfshanyue** [comment]
sorry for the delay.
thanks for pointiing it out and I'll resolve it.
@AllThingsSmitty @byronlun

**Comment by AllThingsSmitty** [comment]
@shfshanyue already resolved with commit 74f7b396a7e5d8207af125c29f34cb8ea5e363e2
