### ISSUE TITLE
2 points contradict each other 

### ISSUE THREAD

**Issue by IAmAdamTaylor** [AllThingsSmitty/css-protips#67]
Use the "Lobotomized Owl" Selector and Consistent Vertical Rhythm are basically the same protip. 

By applying the LobOwl selector you get a consistent vertical rhythm and the benefit of no left over margins at the top or bottom of the containing element. 

With the example presented for Consistent Vertical Rhythm, some margin will be leftover on the last element (unless using the :not trick of course).

I suggest the Consistent Vertical Rhythm tip be removed and a little more explanation added to the LobOwl tip.

**Comment by davidpustai** [comment]
Exactly. I usually write the owl margins inside a scope (since I don't want to apply it to the whole document).

So either remove it or change it to something like `.intro > * + * { margin-top: 1.25rem; }`.

**Comment by Ajmal-hassan** [comment]
The lobotomized owl selector looks like this: * + *
Despite its irreverent name and precarious form, the lobotomized owl selector is no mere thought experiment for me. It is the result of ongoing experimentation into automating the layout of flow content. The owl selector is an “axiomatic” selector with a voracious purview.

All elements in the flow of the document that proceed other elements must receive a top margin of one line.
* + * {
	margin-top: 1.5em;
}
![image](https://user-images.githubusercontent.com/27430342/47543996-cc100d00-d899-11e8-9e58-dad8bf2adfa8.png)
![image](https://user-images.githubusercontent.com/27430342/47544013-d7633880-d899-11e8-94cc-e40aac870eb8.png)

**Comment by AllThingsSmitty** [comment]
Sorry for the delay, yup, I'm on it.
