### ISSUE TITLE
optimizeLegibility has performance implications

### ISSUE THREAD

**Issue by keithjgrant** [AllThingsSmitty/css-protips#7]
You should probably add a note to use optimizeLegibility selectively, rather than blindly applying it to everything. Otherwise, it has performance implications: https://bocoup.com/weblog/text-rendering/

**Comment by AllThingsSmitty** [comment]
@keithjgrant thanks for that link, good information to include.

**Comment by AllThingsSmitty** [comment]
Added with https://github.com/AllThingsSmitty/css-protips/commit/43e82e58e7649c0d233250fe04b59f26fd2918ba.
