### ISSUE TITLE
"Use max-height for Pure CSS Sliders" Needs a Note on the max-height attributes value's impact on the animation

### ISSUE THREAD

**Issue by zacharybrady** [AllThingsSmitty/css-protips#8]
The transition property is detailing how long it will take to reach the max-height value. In your example it would take 0.3 seconds to reach 1000px. If the element's height is much smaller, like 200px, the animation will be so quick you won't notice it and might as well not be using the transition property. I can show you live examples if necessary.

**Comment by AllThingsSmitty** [comment]
@zacharybrady thanks for the suggestion. I think a comment in the CSS would be sufficient: `transition: .3s ease; /* duration: time to reach max-height */`.

**Comment by zacharybrady** [comment]
Yeah, its up to you in the end. I just know from experience that when you want very explicit control over animation timing this technique needs to be used smartly. For instance, don't just go with the largest value for max-height you can think of. Aim for something closer to what you believe the standard height may be while allowing for wiggle room.

**Comment by AllThingsSmitty** [comment]
Addressed with https://github.com/AllThingsSmitty/css-protips/commit/5b60b3ab223f1919da48892d9561540d91337acc.
