### ISSUE TITLE
German translation formatting

### ISSUE THREAD

**Issue by AllThingsSmitty** [AllThingsSmitty/css-protips#84]
@Unruly-MAC I was looking over the merged file for the German translation and there are some formatting issues. It looks like the table of contents hasn't been formatted correctly, and links and code snippets aren't in the proper format either. Can you look into that?

**Comment by AllThingsSmitty** [comment]
I"m going to remove the German translation for now. If you get a chance to work on it and resolve the issue with formatting and broken links, please submit another PR. Thanks.

**Comment by Unruly-MAC** [comment]
Okay I am going to make changes over the night
